create table if not exists public.streamlit_users (
    id bigint generated by default as identity primary key,
    email text unique not null,
    password text not null,
    role text not null default 'user',
    created_at timestamptz not null default now()
);

alter table public.streamlit_users enable row level security;

create policy "InsightAI service key access"
on public.streamlit_users
for all
to service_role
using (true)
with check (true);